import { NextResponse } from "next/server";
import db from "@/lib/db";
import { parse, buildSvg, DEFAULT_OPTS, DEFAULT_LAYOUT } from "@/lib/svg-renderer";
import type { Opts, Layout } from "@/lib/svg-renderer";

export const dynamic = "force-dynamic";

export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)) {
    return NextResponse.json({ error: "Invalid ID" }, { status: 400 });
  }

  const { rows } = await db.query("SELECT code, settings, title FROM diagrams WHERE id = $1", [id]);
  if (!rows.length) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const { code, settings, title } = rows[0];
  if (!code?.trim()) return NextResponse.json({ error: "No code" }, { status: 400 });

  // Merge saved settings with defaults
  const opts: Opts = { ...DEFAULT_OPTS, ...(settings?.opts ?? {}) };
  const layout: Layout = { ...DEFAULT_LAYOUT, ...(settings?.layout ?? {}) };

  // Generate SVG using the extracted renderer
  const diagram = parse(code);
  const svg = buildSvg(diagram, opts, layout);

  // Build a self-contained HTML page that looks like a PDF document
  const html = `<!DOCTYPE html>
<html><head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${(title || "Diagram").replace(/</g, "&lt;")}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  @page { size: landscape; margin: 0.4in; }
  body { background: #f1f5f9; font-family: -apple-system, system-ui, sans-serif; }
  .page { background: #fff; max-width: 1200px; margin: 32px auto; border-radius: 8px; box-shadow: 0 4px 24px rgba(0,0,0,0.08); border: 1px solid #e2e8f0; padding: 48px 56px; }
  .header { border-bottom: 2px solid #e2e8f0; padding-bottom: 16px; margin-bottom: 24px; }
  h1 { font-size: 26px; font-weight: 700; color: #0f172a; }
  .meta { font-size: 12px; color: #94a3b8; margin-top: 4px; }
  .diagram { overflow: auto; display: flex; justify-content: center; }
  .diagram svg { max-width: 100%; height: auto; }
  .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e2e8f0; display: flex; justify-content: space-between; font-size: 10px; color: #94a3b8; }
  .actions { position: fixed; top: 16px; right: 16px; display: flex; gap: 8px; z-index: 10; }
  .actions button, .actions a { padding: 8px 18px; border-radius: 8px; font-size: 13px; font-weight: 600; cursor: pointer; text-decoration: none; border: 1px solid #e2e8f0; font-family: inherit; }
  .btn-pdf { background: #1e293b; color: #fff; border: none; }
  .btn-edit { background: #fff; color: #334155; }
  @media print { .actions { display: none !important; } .page { box-shadow: none; border: none; margin: 0; } body { background: #fff; } }
</style>
</head><body>
<div class="actions">
  <button class="btn-pdf" onclick="window.print()">Save as PDF</button>
  <a class="btn-edit" href="/?id=${id}">Open in Editor</a>
</div>
<div class="page">
  <div class="header">
    <h1>${(title || "Untitled").replace(/</g, "&lt;")}</h1>
    <div class="meta">${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })} · diagrams-bheng.vercel.app</div>
  </div>
  <div class="diagram">${svg}</div>
  <div class="footer">
    <span>Generated by Diagrams</span>
    <span>${id}</span>
  </div>
</div>
</body></html>`;

  return new Response(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "public, max-age=60",
    },
  });
}

